name: Rust

on:
  push:
    branches: [ ]
    # branches: [ "main" ]
  pull_request:
    # Disabled until I find a way to download the required maps for testing without breaking the EULA/TOS from Valve
    # branches: [ "main" ]
    branches: [ ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
